export default {
  SMART_PLAN_HUB_LOGO: require('./smartPlanHubLogo.png'),
  GOOGLE: require('./google.png'),
  FACEBOOK: require('./facebook.png'),
  SEARCH_ICON: require('./searchIcon.png'),
  LOGOUT: require('./logout.png'),
  BACK_ARROW: require('./back.png'),
  MENU: require('./menu.png'),
  HOME: require('./home.png'),
  SETTINGS: require('./settings.png'),
  NOTIFICATION: require('./notification.png'),
  DOLLAR: require('./dollar-symbol.png'),
  CALENDAR: require('./calendar.png'),
  EDIT: require('./edit.png'),
  BOLT: require('./flash.png'),
  STAR: require('./star.png'),
  CUSTOMER_REVIEW: require('./customer-review.png'),
  TICKET: require('./ticket.png'),
  STORE: require('./store.png'),
  PEOPLE: require('./people.png'),
  ANALYTICS: require('./analytics.png'),
  ADMIN: require('./administrator.png'),
  CHAT: require('./chat.png'),
};
